name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      AWS_IAM_ARN: ${{ secrets.AWS_IAM_ARN }}
      TOOLKIT_STACK: CDKToolkit-poll-position
      STACK_NAME: PollPositionStack
      UI_STACK_NAME: PollPositionUIStack
      BOOTSTRAP_QUALIFIER: pollpstn
      BUILD_TIMESTAMP: ${{ github.run_id }}-${{ github.run_number }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install
          cd infrastructure && npm install

      - name: Authenticate Docker with ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

      - name: Ensure ECR Repositories Exist
        run: |
          aws ecr describe-repositories --repository-names poll-position --region $AWS_REGION || \
          aws ecr create-repository --repository-name poll-position --region $AWS_REGION
          aws ecr describe-repositories --repository-names poll-position-api --region $AWS_REGION || \
          aws ecr create-repository --repository-name poll-position-api --region $AWS_REGION
          aws ecr describe-repositories --repository-names poll-position-ui --region $AWS_REGION || \
          aws ecr create-repository --repository-name poll-position-ui --region $AWS_REGION

      # --- Backend Services ---
      - name: Build and Push Backend Docker Images
        run: |
          docker build -t poll-position-ingest -f services/ingest/Dockerfile services/ingest
          docker tag poll-position-ingest:latest ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/poll-position:latest
          docker push ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/poll-position:latest

          docker build -t poll-position-api -f services/api/Dockerfile services/api
          docker tag poll-position-api:latest ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/poll-position-api:latest
          docker push ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/poll-position-api:latest

      # --- Infrastructure Deployment ---
      - name: List CDK Stacks (for debug)
        working-directory: infrastructure
        run: npx cdk ls

      - name: Validate CDK Bootstrap Qualifier
        run: |
          ACTUAL_QUALIFIER=$(aws cloudformation describe-stacks \
            --stack-name $TOOLKIT_STACK \
            --region $AWS_REGION \
            --query "Stacks[0].Parameters[?ParameterKey=='Qualifier'].ParameterValue" \
            --output text)

          echo "Found bootstrap qualifier: $ACTUAL_QUALIFIER"

          if [ "$ACTUAL_QUALIFIER" != "$BOOTSTRAP_QUALIFIER" ]; then
            echo "Mismatch: expected '$BOOTSTRAP_QUALIFIER' but found '$ACTUAL_QUALIFIER'"
            exit 1
          fi

      - name: Validate CDK App Configuration
        working-directory: services/infrastructure
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          ACTUAL=$(jq -r '.app' cdk.json)
          EXPECTED="npx ts-node --prefer-ts-exts bin/poll-position.ts"

          if [[ "$ACTUAL" != "$EXPECTED" ]]; then
            echo "Error: cdk.json 'app' is misconfigured."
            echo "Expected: $EXPECTED"
            echo "Found:    $ACTUAL"
            exit 1
          else
            echo "cdk.json app configuration is correct."
          fi

      # --- Frontend (UI) Build and Deploy FIRST ---
      - name: Build UI Docker image
        working-directory: services/ui
        run: |
          docker build \
            --no-cache \
            --build-arg VITE_API_BASE_URL=http://localhost:3000 \
            -t poll-position-ui \
            -f Dockerfile .

      - name: Tag and Push UI Docker image to ECR
        run: |
          docker tag poll-position-ui:latest ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/poll-position-ui:latest
          docker push ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/poll-position-ui:latest

      - name: Deploy UI CDK Stack (first to create export)
        working-directory: infrastructure
        run: |
          npx cdk deploy \
            --toolkit-stack-name $TOOLKIT_STACK \
            --context bootstrapQualifier=$BOOTSTRAP_QUALIFIER \
            $UI_STACK_NAME \
            --require-approval never

      # --- Main Stack Deploy (after UI) ---
      - name: Deploy Main CDK Stack
        working-directory: infrastructure
        run: |
          npx cdk deploy \
            --toolkit-stack-name $TOOLKIT_STACK \
            --context bootstrapQualifier=$BOOTSTRAP_QUALIFIER \
            $STACK_NAME \
            --require-approval never
